on:
  push:
    tags:
     - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: build-and-release
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - run: gradle bintrayUpload
       env:
         BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
         BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
