on:
  push:
    tags:
     - '*'

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: build-and-release
    steps:
     - uses: actions/checkout@v2
     - run: echo $BINTRAY_USER
     - run: gradle bintrayUpload


